#!/bin/bash

HOST=localhost
LOGIN="lynn"
PASSWORD="Pusyux8484"
DATABASE="hydrobus_belfortain"

cp app.py test_app.py

sed -i "s/host=.*/host=\"${HOST}\",/g" test_app.py
sed -i "s/user=.*/user=\"${LOGIN}\",/g" test_app.py
sed -i "s/password=.*/password=\"${PASSWORD}\",/g" test_app.py
sed -i "s/database=.*/database=\"${DATABASE}\",/g" test_app.py


